### ISSUE TITLE
Shelly  3EM communication fails

### ISSUE THREAD

**Issue by jep342** [sbender9/signalk-shelly#18]
Using the Shelly 3EM for monitoring AC lines works initially, but after some variable amount of time, data is no longer being received.  Typically, this is in the range of 2 - 5 minutes. Rebooting the SignalK-server restores the communication only to repeat the cycle.     Device is still active when checked by connecting to the ip address of the Shelly 3EM.  Once the communication stops, switching the relay on the Shelly does not change the bool key or any other data from the Shelly.

npm v 7.15
signalk-shelly v 1.6.2
signalk-server v1.40
shelly 3EM firmware v 20210429-102318/v1.10.4-g3f94cd7 
hardware = Raspberry Pi 4b

Thank you for any help you may be able to provide and a many more thanks for the amazing work you and others have contributed to the signalk projects.

Jim Pope

**Comment by jep342** [comment]
Scott,  Suspect that my issue isn't with the plugin as deeper dive into logs show the app.handleMessage(plugin.id, { updates:...  from this plugin are working fine until what appears to be an unrelated bad N2K message occurs.  This message stream from the log (showing the message before and after culprit), is

        1626385906555;A;2021-07-15T21:51:46.554Z,6,127508,224,255,8,04,fe,ff,ff,7f,ff,ff,57
        1626385906555;A;2021-07-15T21:51:46.555Z,0,0,4,0,8,00,01,00,00,00,00,00,00
        1626385906565;A;2021-07-15T21:51:46.555Z,6,127506,224,255,8,01,38,ff,ff,ff,ff,ff,ff

That generates the error message from the server of
**Jul 15 17:51:46 TypeError [ERR_INVALID_ARG_TYPE]: The "target" argument must be an instance of Buffer or Uint8Array. Received undefined at _copy (buffer.js:212:11) at Buffer.copy (buffer.js:769:12) at Parser._parse (/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:169:26) at Parser.parseString (/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:395:24) at Parser.parse (/usr/local/lib/node_modules/signalk-server/node_modules/@canboat/canboatjs/lib/fromPgn.js:269:19) at CanboatJs._transform (/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/streams/canboatjs.js:49:34) at CanboatJs.Transform._read (internal/streams/transform.js:205:10) at CanboatJs.Transform._write (internal/streams/transform.js:193:12) at writeOrBuffer (internal/streams/writable.js:358:12) at CanboatJs.Writable.write (internal/streams/writable.js:303:10) at Log.ondata (internal/streams/readable.js:745:22) at Log.emit (events.js:376:20) at addChunk (internal/streams/readable.js:309:12) at readableAddChunk (internal/streams/readable.js:284:9) at Log.Readable.push (internal/streams/readable.js:223:10) at Log.Transform.push (internal/streams/transform.js:166:32) { code: 'ERR_INVALID_ARG_TYPE' }** 

After this, no additional app.handleMessage(plugin.id, { updates:...  from this plugin are received until server is rebooted.

N2K hardware in this case is a PiCan-M board.  I haven't tried it yet with my Actisense.  I will also uninstall the shelly plugin and confirm that the bad N2K message is showing up.  At this point, i suspect it will still be there.

Jim

**Comment by jep342** [comment]
As suspected, errant message was still present. 
Problem solved.
